star_social/group/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CreateGroupView, GroupListView, GroupDetailView, JoinGroup, LeaveGroup

app_name = "group"

urlpatterns = [
    path('new/', CreateGroupView.as_view(), name="create_group"),
    path('', GroupListView.as_view(), name="list_group"),
    path('<slug>', GroupDetailView.as_view(), name="group_detail"),
    path('member/add/<slug>', JoinGroup.as_view(), name="add_member"),
    path('member/remove/<slug>', LeaveGroup.as_view(), name="remove_member"),

]

star_social/post/urls.py
from django.contrib import admin
from django.urls import path
from .views import ListUserPosts, CreatePost, PostDetailView, PostDeleteView

app_name='post'

urlpatterns = [
    path('by/<slug:user>', ListUserPosts.as_view(), name="list_posts"),
    path('new/', CreatePost.as_view(), name="create_post"),
    path('by/<slug:user>/<int:pk>', PostDetailView.as_view(), name="post_detail"),
    path('by/<slug:user>/<int:pk>/remove', PostDeleteView.as_view(), name="post_delete"),

    
]

star_social/star_social/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homeView.as_view(), name='home'),
    path('post/', include("post.urls")),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    # Think you need this if you dont pass template_name to logoutView
    # path('accounts/', include("django.contrib.auth.urls")),
    path('group/', include("group.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

star_social/group/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth import get_user_model
# This method replaces spaces with hyphens and lowercases strings
from django.utils.text import slugify

# This python library allows people to write markdown in the description
import misaka

# https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#extending-the-existing-user-model
# https://stackoverflow.com/questions/45499641/django-custom-user-model-best-practice-user-get-user-model
# This function returns the currently active user model i.e. the custom one. Refer to above links on creating custom user model - it is recommended apparently
User = get_user_model()

class Group(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(max_length=512, blank=True, default='')
    # NB: i believe description_html will not show up in admin because it is editable=False
    description_html = models.TextField(max_length=512, editable=False, blank=True, default='')
    # Will use this in group detail view, must have button that will add user to the current group
    # Check part six here
    users = models.ManyToManyField(User)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("group:group_detail", kwargs={"slug": self.slug})
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["name"]

star_social/group/forms.py
from django import forms
from django.db.models import fields
from .models import Group
from django.utils.translation import gettext_lazy as _

class GroupForm(forms.ModelForm):
    
    class Meta:
        model = Group
        exclude = ['users', 'slug', 'description_html']

        labels = {
                'name': _('Name'),
            }
        # help_texts = {
        #     'name': _('Some useful help text.'),
        # }
        # error_messages = {
        #     'name': {
        #         'max_length': _("This writer's name is too long."),
        #     },
        # }

    # https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/
    # widgets = {
    #         'name': forms.Textarea(attrs={'placeholder':'name'}),
    #     }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #The style attribute should be placed in css file
        self.fields['name'].widget.attrs.update({'class': 'text_input', 'placeholder':'Name'})
        self.fields['description'].widget.attrs.update({'class': 'text_input','placeholder':'Description'})

    

star_social/group/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls.base import reverse
from django.views.generic import (TemplateView, ListView, DeleteView, CreateView, DetailView, UpdateView, RedirectView)
from django.views.generic.edit import FormView
from .models import Group
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import GroupForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib import messages

class CreateGroupView(LoginRequiredMixin, CreateView):
    login = 'accounts/login.html'

    template_name = 'group/create_group.html'
    form_class = GroupForm
    model = Group
    # success_url = reverse_lazy("")

    def form_valid(self, form):
        form = self.get_form()
        group_object = form.save()
        group_object.users.add(self.request.user)
        return super().form_valid(form)

class GroupListView(ListView):
    
    model=Group
    template_name = 'group/group_list.html'

    # def get_queryset(self):
    #     return super().get_queryset()

class GroupDetailView(DetailView):

    model=Group
    template_name = 'group/group_detail.html'

    # NOTE: Dont need this as it can be done in template itself using {% if user in group.users.all %}
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     current_user = self.request.user
    #     current_group = self.get_object()
    #     if current_user in current_group.users.all():
    #         context['is_member'] = True
    #     else:
    #         context['is_member'] = False
    #     return context

class JoinGroup(LoginRequiredMixin, RedirectView):
    login = 'accounts/login.html'

    def get_redirect_url(self, *args, **kwargs):
        return reverse('group:group_detail', kwargs={'slug': kwargs['slug']})

    def get(self, request, *args, **kwargs):
        try:
            group_object = Group.objects.get(slug=kwargs['slug'])
        except:
            # To display messages, need to include relevant template tags in templates.
            messages.warning(self.request,"Warning, you are already a member of this group")
        else:
            group_object.users.add(request.user)
            group_object.save()
        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, RedirectView):
    login = 'accounts/login.html'

    def get_redirect_url(self, *args, **kwargs):
        return reverse('group:group_detail', kwargs={'slug': kwargs['slug']})

    def get(self, request, *args, **kwargs):
        try:
            group_object = Group.objects.get(slug=kwargs['slug'])
        except:
            messages.warning(self.request,"Warning, you are not a member of this group")
        else:
            group_object.users.remove(request.user)
            group_object.save()
        return super().get(request, *args, **kwargs)
        
# @login_required
# def group_member_add(request, slug):
#     # print("group add")
#     group_object = Group.objects.get(slug=slug)
#     # print(group_object)
#     group_object.users.add(request.user)
#     group_object.save()
#     # print(group_object.users.all())
#     return HttpResponseRedirect(reverse("group:group_detail", kwargs={'slug':group_object.slug}))

# @login_required
# def group_member_remove(request, slug):
#     # print("group remove")
#     group_object = Group.objects.get(slug=slug)
#     # print(group_object)
#     group_object.users.remove(request.user)
#     group_object.save()
#     # print(group_object.users.all())
#     return HttpResponseRedirect(reverse("group:group_detail", kwargs={'slug':group_object.slug}))

star_social/group/templates/group/create_group.html
{% extends 'base.html' %}

{% block body_block %}

    <h1>Create a New Group</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" value="Create">
    <form>

{% endblock body_block %}

star_social/group/templates/group/group_detail.html
{% extends 'base.html' %}

{% block body_block %}

    <h1>{{group.name}}</h1>
    <p>{{group.description}}</p>
    <h2>Member count: {{group.users.count}}</h2>
    {% comment %} {% if is_member %} {% endcomment %}
    {% if user in group.users.all %}
        <a href="{% url 'group:remove_member' slug=group.slug %}"><button type="button" class="btn btn-warning"><i class="bi bi-x-circle"></i></i> Leave</button></a>
    {% else %}
        <a href="{% url 'group:add_member' slug=group.slug %}"><button type="button" class="btn btn-warning"><i class="bi bi-person-plus"></i> Join</button></a>
    {% endif %}

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        {% endfor %}
    </div>
    {% endif %}

    <br>

    <div class="post_table">
        {% if group.posts.count == 0 %}
            <h2>There are no posts in this group yet.</h2>
        {% else %}
        {% comment %} <table >
            {% for post in group.posts.all %}
            <tr style=" vertical-align: text-top;">
                <td>
                    <a href="{% url 'post:list_posts' user=post.user %}"><h3>@{{post.user}}</h3></a>
                </td>
                <td style="padding-left: 2em;">
                    <p>{{post.content_html|safe}}</p>
                    <p><a href="{% url 'post:post_detail' user=post.user pk=post.pk %}">{{post.create_date}}</a> in {{post.group}}</p>
                    <a href="{% url 'post:post_delete' user=post.user pk=post.pk%}"><p class="delete_post_text"><i class="bi bi-x-circle-fill"></i> Delete</p></a>
                </td>
            </tr>
            {% endfor %}
        </table> {% endcomment %}
        <table >
            {% for post in group.posts.all %}
            {% comment %} The include keyword pulls _post.html in here and passes all parameters after the 'with' keyword as context variables {% endcomment %}
                {% include 'post/_post.html' with post=post hide_delete=False %}
            {% endfor %}
        </table>
        {% endif %}
    </div>

{% endblock body_block %}

star_social/group/templates/group/group_list.html
{% extends 'base.html' %}

{% block body_block %}

    <div class="row justify-content-center">
        <div class="col-md-4">
            {% if user.is_authenticated %}
                <h1>Welcome back</h1>
                <a href="{% url 'post:list_posts' user=user.username %}"><h1 class="link">@{{user}}</h1></a>
            {% endif %}
            <h1>Groups</h1>
            <p>Welcome to the Groups Page!<br>Select a Group with a shared interest!</p>
            {% if user.is_authenticated %}
                <a href="{% url 'group:create_group'%}"><button type="button" class="btn btn-warning"><i class="bi bi-plus-square"></i> Create New Group!</button></a>
            {% endif %}
        </div>

        <div class="col-md-8 group_list_container">
            {% if group_list.count == 0 %}
                <h2 class="group_list_text">There are no groups to display</h2>
            {% else %}
                {% for group in group_list %}
                    <a href="{% url 'group:group_detail' slug=group.slug %}"><h3 class="group_list_text">{{group.name}}</h3></a>
                    {% comment %} description_html is being displayed as white text, that is why you cant see it. Need to somehow change color of text {% endcomment %}
                    <p>{{group.description_html|safe}}</p>
                    <div class="row justify-content-left">
                    <div class="col-4">
                        <p class="group_list_subtext"><span class="num_icon">{{group.users.count}}</span> member</p> 
                    </div>
                    <div class="col-4">
                        <p class="group_list_subtext"><span class="num_icon">{{group.posts.count}}</span> posts</p>
                    </div>
                    </div>
                    <br>
                {% endfor %}
            {% endif %}
        </div>
    </div>

{% endblock body_block %}