star_social/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts.views import CreateUser
from .forms import CustomAuthenticationForm

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', authentication_form=CustomAuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'), #The template_name provided here is the html to be displayed after logout has occurred
    # Include other auth_views here 
    path('register/', CreateUser.as_view(), name='register'),

]

star_social/group/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CreateGroupView, GroupListView, GroupDetailView, JoinGroup, LeaveGroup

app_name = "group"

urlpatterns = [
    path('new/', CreateGroupView.as_view(), name="create_group"),
    path('', GroupListView.as_view(), name="list_group"),
    path('<slug>', GroupDetailView.as_view(), name="group_detail"),
    path('member/add/<slug>', JoinGroup.as_view(), name="add_member"),
    path('member/remove/<slug>', LeaveGroup.as_view(), name="remove_member"),

]

star_social/post/urls.py
from django.contrib import admin
from django.urls import path
from .views import ListUserPosts, CreatePost, PostDetailView, PostDeleteView

app_name='post'

urlpatterns = [
    path('by/<slug:user>', ListUserPosts.as_view(), name="list_posts"),
    path('new/', CreatePost.as_view(), name="create_post"),
    path('by/<slug:user>/<int:pk>', PostDetailView.as_view(), name="post_detail"),
    path('by/<slug:user>/<int:pk>/remove', PostDeleteView.as_view(), name="post_delete"),

    
]

star_social/star_social/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import homeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homeView.as_view(), name='home'),
    path('post/', include("post.urls")),
    path('accounts/', include("accounts.urls", namespace='accounts')),
    # Think you need this if you dont pass template_name to logoutView
    # path('accounts/', include("django.contrib.auth.urls")),
    path('group/', include("group.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

star_social/accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):

    def __str__(self) -> str:
        return "@{}".format(super.username)

star_social/accounts/forms.py
from django.forms import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# This form extends UserCreationForm to include email field
# https://docs.djangoproject.com/en/4.0/topics/auth/customizing/#custom-users-and-the-built-in-auth-forms
class CustomUserCreationForm(UserCreationForm):
    
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #The style attribute should be placed in css file
        self.fields['username'].widget.attrs.update({'class': 'text_input','placeholder':'username'})
        self.fields['username'].label = 'Display Name'
        self.fields['email'].widget.attrs.update({'class': 'text_input','placeholder':'someone@gmail.com'})
        # /home/phoenix/python_env/myDjango/lib/python3.9/site-packages/django/contrib/auth/forms.py
        self.fields['password1'].widget.attrs.update({'class': 'text_input','placeholder':'Password'})
        self.fields['password2'].widget.attrs.update({'class': 'text_input','placeholder':'Password'})

# https://www.notimedad.dev/customizing-django-builtin-login-form/
class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'text_input','placeholder':'Username'})
        self.fields['password'].widget.attrs.update({'class': 'text_input','placeholder':'Password'})

star_social/accounts/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

# Create your views here.
# https://docs.djangoproject.com/en/3.2/ref/class-based-views/generic-editing/#formview
# NOTE: class that inherits Formview will not automatically create new user object, it is only meant to retrive form data. You have to do that yourself in valid_form
# class CreateUser(FormView):
#     template_name = "accounts/registration.html"
#     form_class = CustomUserCreationForm
#     success_url = reverse_lazy('accounts:login')

#     def form_valid(self, form) -> HttpResponse:
#         # https://docs.djangoproject.com/en/4.0/ref/forms/api/
#         email = form.cleaned_data['email']
#         new_user = form.save(commit=False)
#         new_user.email = email
#         new_user.save()
#         return super().form_valid(form)

# Or can inherit creatview instead. Note that you do not have to give it model attribute.
class CreateUser(CreateView):
    template_name = "accounts/registration.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('accounts:login')

star_social/accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load static %}
{% load django_bootstrap5 %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/star_social.css' %}">

    {% comment %} Font import {% endcomment %}

    {% comment %} Bootstrap icons {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    
    <title>Star Social</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark luxury_font">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'accounts:home' %}">Star Social</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">About</a>
              </li>
            </ul>

            <ul class="navbar-nav ms-auto">

              {% if not user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'group:list_group' %}">Groups</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">Signup</a>
              </li>

              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'post:create_post' %}">Post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'group:list_group' %}">Groups</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'group:create_group' %}">Create Group</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              </li>
              {% endif %}

            </ul>
          </div>
        </div>
      </nav>

      <div class="container-lg">
        <div class="row justify-content-center">
          <div class="col-10 navbar_break" style="padding-top: 2em">
            {% block body_block %}
            
            {% endblock body_block %}
          </div>
        </div>
      </div>

    <div id="particles-js"></div>
    <script src="{% static 'js/particles.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script> 

</body>
</html>

star_social/accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block body_block %}
    {% if user.is_authenticated %}
        <h1>You are now logged in!</h1>
        <a href="{% url 'group:list_group' %}"><h1 class="link">Go to Groups</h1></a>
    {% else %}
        <h1>Welcome to star social!</h1>
    {% endif %}

{% endblock body_block %}

star_social/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body_block %}

<h1>Login</h1>

{% if form.errors %}
<p>Your username and password didn't match. Please py again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
{% csrf_token %}

<p>{{ form.username.label_tag }}</p>
<p>{{ form.username }}</p>
<p>{{ form.password.label_tag }}</p>
<p>{{ form.password }}</p>


<input class="btn btn-primary" type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you set up the password_reset view in your URLconf #}
{% comment %} <p><a href="{% url 'password_reset' %}">Lost password?</a></p> {% endcomment %}

{% endblock body_block %}

star_social/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body_block %}
<h1>Thanks for visiting! Come back soon!</h1>
{% endblock body_block %}

star_social/accounts/templates/accounts/registration.html
{% extends 'base.html' %}

{% block body_block %}
    <h1>Sign Up</h1>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>

{% endblock body_block %}